# Generated by Django 4.1.7 on 2023-02-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', 'initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='firstModelPost',
        ),
    ]
